main: de.jaylawl.awayfromminecraft.AwayFromMinecraft
name: AwayFromMinecraft
version: 0.dev1
author: jaylawl
website: https://github.com/jaylawl
commands:
  awayfromminecraft:
    aliases: [afm]
    permission: "awayfromminecraft.admin"
    permission-message: "§cInsufficient permission"
  isafk:
    permission: "awayfromminecraft.admin"
    permission-message: "§cInsufficient permission"
  listafk:
    aliases: [afklist]
    permission: "awayfromminecraft.admin"
    permission-message: "§cInsufficient permission"