main: de.jaylawl.awayfromminecraft.AwayFromMinecraft
name: AwayFromMinecraft
version: 0.dev3
author: jaylawl
website: https://github.com/jaylawl
commands:
  awayfromminecraft:
    aliases: [afm]
    permission: "awayfromminecraft.admin"
    permission-message: "§cInsufficient permission"
  isafk:
    permission: "awayfromminecraft.check"
    permission-message: "§cInsufficient permission"
  listafk:
    aliases: [afklist]
    permission: "awayfromminecraft.check"
    permission-message: "§cInsufficient permission"
  kickafk:
    aliases: [afkkick]
    permission: "minecraft.command.kick"
    permission-message: "§cInsufficient permission"